SPORTSHUB-206 Add loggers
owya490/social-sports pull request #148
Opened 2024-08-06 09:04 UTC by 41dan

## Why was your change needed?

So we can log whats actually going on when users have issues

## What was Changed?

Please detail here what were the main changes you made.

## Any extra notes for reviewers to know?

Write any extra notes you may have for the PR.
This may include specific code paths that need extra scrutiny, or how to review a specific portion of code.

2024-08-06 12:37 UTC, Edwin-Ni commented on frontend/app/(footer)/profile/page.tsx
> +      profileLogger.info(`Edited profile ${editedData}`);
Maybe include the userId with it

2024-08-06 12:38 UTC, Edwin-Ni commented on frontend/components/Filter/FilterBanner.tsx
> +      filterBannerLogger.info(`Location ${srcLocation}`);
What is the purpose of logging this?

2024-08-06 12:40 UTC, 41dan commented on frontend/app/(footer)/profile/page.tsx
> +      profileLogger.info(`Edited profile ${editedData}`);
okies thankyou

2025-01-05 09:08 UTC, brian2w commented on frontend/components/navbar/SearchBar.tsx
> +    searchBarLogger.info(`Event:${event}, Location:${location}`);
I'm thinking we shouldn't need to log this unless we want metrics for future marketing on what are the most common search terms

2025-01-05 09:13 UTC, brian2w commented on frontend/services/src/events/eventsService.ts
> +    eventServiceLogger.info(`Deleting Event by Name successfull ${eventName}`);
it would be more useful to log the eventId for each of these.

I think a lot of these console log statements have been put here originally for coding and debugging purposes.

2025-01-05 09:14 UTC, brian2w requested changes
noice, ty for doing this, just some brief comments on some general changes i think would be good

2025-07-28 14:06 UTC, closed without merging