SPORTSHUB-81 Support float pricing
owya490/social-sports pull request #163
Opened 2024-08-17 17:25 UTC by owya490

now we can have $18.88 as the price for events.

Events are now stored as cents in the database.

2024-08-18 00:15 UTC, brian2w commented
There are a couple of current TODO's with the following comment
<img width="879" alt="image" src="https://github.com/user-attachments/assets/6576b0aa-c81a-4078-8250-886acabe19ad">
Do these need to be changed as well for price?

2024-08-18 00:16 UTC, brian2w requested changes

2024-08-18 00:16 UTC, brian2w commented on frontend/utilities/priceUtils.ts
> +export function displayPrice(price: number): number {
Put a short doc above this function seeing that this is used extensively throughout the codebase.

2024-08-18 10:43 UTC, ReggieStar11 reviewed
looks good just fix up brians comments

2024-08-19 11:04 UTC, brian2w approved these changes
lgtm

2024-08-19 11:09 UTC, ReggieStar11 approved these changes

2024-08-19 11:09 UTC, merged