SPORTHUB-290 Delete Event
owya490/social-sports pull request #212
Opened 2024-11-18 09:32 UTC by inzaenity

Delete Event, deploy function by using gcp console

2024-11-18 10:30 UTC, ReggieStar11 commented on frontend/components/organiser/EventDrillDownSettingsPage.tsx
> +        console.log("sendgrid error", error);
remove this

2024-11-18 10:30 UTC, ReggieStar11 commented on frontend/components/organiser/EventDrillDownSettingsPage.tsx
> +    console.log(eventMetadata);
remove this

2024-11-25 11:57 UTC, Edwin-Ni requested changes
Overall looks good, have a look over some comments

2024-12-08 09:37 UTC, Edwin-Ni commented on functions/lib/sendgrid/delete_event_organiser.py
> +
I would just prefer it as:
`
             purchaser_email = purchaser_info.get("email")
             if not purchaser_email:
                logger.error(f"No email found for purchaser {purchaser_id}. Skipping.")
                continue

            

            ticket_count = purchaser_info.get("totalTicketCount")
            if not ticket_count:
                logger.error(f"No tickets found for purchaser {purchaser_id}. Skipping.")
                continue

`

2025-01-13 11:33 UTC, brian2w submitted a review, later dismissed

2025-01-18 10:53 UTC, brian2w commented on functions/lib/.DS_Store
Can we git ignore this file, I think it is standard to not have DS stores in our git repo

2025-01-18 10:59 UTC, brian2w commented on functions/lib/sendgrid/delete_event.py
> +    if event_name is None or event_price is None or organiser_email is None or event_status is None:
should we be checking for the other variables from the `event_delete_data` variable to ensure they are not null as well 🤔

2025-01-18 11:05 UTC, brian2w commented on functions/lib/sendgrid/delete_event.py
> +        try:
are we planning on implementing retries for failed emails?

2025-01-28 06:04 UTC, brian2w commented on frontend/components/organiser/EventDrilldownSettingsPage.tsx
> +      await archiveAndDeleteEvent(eventId, user.userId);
ah yep you're right about that

2025-01-28 06:04 UTC, brian2w commented on frontend/components/organiser/EventDrilldownSettingsPage.tsx
> +      bustEventsLocalStorageCache();
ah got it

2025-02-22 10:57 UTC, brian2w commented on frontend/services/src/events/eventsService.ts
>  export async function deleteEvent(eventId: EventId): Promise<void> {
should we remove this function?

2025-03-02 05:51 UTC, brian2w commented on firestore.rules
> +      allow read: if request.auth != null;
hmm I'm not seeing this change on my end 🤔

2025-03-06 12:22 UTC, owya490 commented on frontend/components/elements/HighlightButton.tsx
> +        `px-33222 py-1 rounded-lg font-semibold whitespace-nowrap bg-white text-black hover:bg-black hover:text-white border-2 border-black transition-colors duration-300 transform ` +
why is this px-33222

2025-03-06 12:35 UTC, owya490 commented on frontend/components/organiser/EventDrilldownSettingsPage.tsx
> +    console.log(eventMetadata);
dude its still a console.log??

2025-03-06 12:36 UTC, owya490 commented on frontend/interfaces/EventTypes.ts
> +}
@inzaenity what do you think?

2025-03-06 12:43 UTC, owya490 commented on frontend/components/organiser/DeleteEventModal.tsx
> +                            An Email will be sent to each attendee notifying them. Please handle refunds within business
why do we have `Please handle refunds within business days` do we mean to have a number here?

2025-03-06 12:45 UTC, owya490 commented on frontend/components/organiser/EventDrilldownSettingsPage.tsx
> +  };
can we add this?

2025-03-06 12:45 UTC, owya490 commented on frontend/components/organiser/EventDrilldownSettingsPage.tsx
> +  };
and for if the delete event has errors?

2025-03-06 12:45 UTC, owya490 commented on frontend/services/src/sendgrid/sendgridService.ts
> +export async function sendEmailonDeleteEvent(eventId: string) {
can you please fix this?

2025-03-06 12:46 UTC, owya490 commented on frontend/components/organiser/EventDrilldownSettingsPage.tsx
> +      await sendEmailonDeleteEvent(eventId);
not changed

2025-03-06 12:49 UTC, owya490 commented on functions/venv/pyvenv.cfg
> -command = /opt/homebrew/opt/python@3.11/bin/python3.11 -m venv /Users/owenyang/Documents/Github/social-sports/functions/venv
can we add this to .gitignore please then?

2025-03-06 12:52 UTC, owya490 commented on functions/main.py
> +from lib.sendgrid.delete_event_organiser import *
there isnt this file anymore right?

2025-03-06 12:53 UTC, owya490 commented on functions/lib/sendgrid/delete_event.py
> +    maybe_delete_event_data = db.collection("DeletedEvents").document(request_data.eventId).get()
will we ever have a race condition here, where the data is not fully replicated to DeleteEvent collection, and this function is invoked?

2025-03-06 12:56 UTC, owya490 commented on functions/lib/sendgrid/delete_event.py
> +        return {"status": 500, "message": "Failed to send organizer email"}
i think can we not fail fast here? we still want to send out purchaser emails, even if the organiser one fails

2025-03-06 12:58 UTC, owya490 commented on functions/lib/sendgrid/delete_event.py
> +                logger.error(f"Failed to send email to {purchaser_email} after {MAX_RETRIES} attempts.")
this is great retry and back off logic, i think 5 seconds is too generous, we can lower this to 1s, as if we have 50 attendees with full failure thats 5 * 3 * 50 = 450 seconds which is nearing the function timeout

2025-03-06 12:58 UTC, owya490 commented on functions/lib/sendgrid/delete_event.py
> +    for purchaser_info in attendees:
we also need to add a jitter here.. or even just a 0.5s sleep, so we don't overload sendgrid servers and get ratelimited. should be proactive here, not just rely on our retry system

2025-03-06 13:33 UTC, owya490 commented on firestore.rules
> +      allow create: if request.auth != null;
change this to write?

2025-03-06 13:33 UTC, owya490 commented on firestore.rules
> +      allow create: if request.auth != null;
nono wait just add 
`allow update: if request.auth != null && resource.data.organiserId == request.auth.uid;`

2025-03-06 13:36 UTC, owya490 commented on frontend/services/src/sendgrid/sendgridService.ts
> +      console.log("this is the", result);
remove this please?

2025-03-06 14:42 UTC, owya490 approved these changes
lgtm!

2025-03-06 14:55 UTC, merged