SPORTSHUB-99 - Create Event Responsive Mobile View
owya490/social-sports pull request #93
Opened 2024-05-17 01:36 UTC by brian2w

## Why was your change needed?

Create event did not have a responsive mobile view.

## What was Changed?

All four pages of the create event frontend workflow have been made to be responsive to mobile.

## Any extra notes for reviewers to know?

Write any extra notes you may have for the PR.
This may include specific code paths that need extra scrutiny, or how to review a specific portion of code.

2024-05-19 14:35 UTC, owya490 commented on frontend/components/events/create/forms/BasicForm.tsx
> +                className="rounded-md focus:ring-0"
thank you for this change `focus:ring-0`

2024-05-19 14:35 UTC, owya490 commented on frontend/components/events/create/DescriptionImageForm.tsx
> +  const [previousImages, setPreviousImages] = useState<string[]>([]);
is this based off reggies changes? is this being merged into master or into reggie's branch?

2024-05-19 14:36 UTC, owya490 approved these changes

2024-05-19 14:37 UTC, owya490 requested changes
check with reggie if these changes r his, and need fixing>?

2024-06-06 05:25 UTC, ReggieStar11 approved these changes

2024-06-06 05:26 UTC, ReggieStar11 approved these changes

2024-06-17 11:59 UTC, owya490 approved these changes

2024-06-17 12:05 UTC, merged